import asyncio
import logging
import inspect
from pydantic import BaseModel
import aiobale
import aiobale.types
import aiobale.types.responses.message as msg_resp_module
from aiobale.client.session.aiohttp import AiohttpSession
from aiobale import Client
from aiobale.enums import ChatType
from config import WHITELISTED_USERS, STARTUP_NOTIFICATION_CHAT

# Configure main application logger
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger("App")

# Propagate aiobale internal logger outputs
for logger_name in logging.root.manager.loggerDict:
    logging.getLogger(logger_name).setLevel(logging.INFO)
    logging.getLogger(logger_name).propagate = True


# ==============================================================================
# ULTIMATE FIX: DEEP NESTED DICT UNWRAPPER & PYDANTIC CONTEXT PATCH
# ==============================================================================
def deep_clean_bale_dict(obj):
    """
    Recursively converts and unwraps dictionary representations with numeric string keys
    (e.g., {'1': ..., '2': ...}) generated by Bale API back into valid Python lists/objects.
    Fixes Pydantic ValidationError for DialogResponse and HistoryResponse in aiobale.
    """
    if isinstance(obj, dict):
        if obj and all(isinstance(k, str) and k.isdigit() for k in obj.keys()):
            sorted_items = [v for k, v in sorted(obj.items(), key=lambda x: int(x[0]))]
            cleaned_list = []
            for item in sorted_items:
                c = deep_clean_bale_dict(item)
                if isinstance(c, list):
                    cleaned_list.extend(c)
                else:
                    cleaned_list.append(c)
            return cleaned_list
        else:
            cleaned_dict = {}
            for k, v in obj.items():
                c_v = deep_clean_bale_dict(v)
                if isinstance(c_v, dict) and list(c_v.keys()) == ['1']:
                    c_v = deep_clean_bale_dict(c_v['1'])
                cleaned_dict[k] = c_v
            return cleaned_dict
    elif isinstance(obj, list):
        cleaned_list = []
        for item in obj:
            c = deep_clean_bale_dict(item)
            if isinstance(c, dict) and list(c.keys()) == ['1']:
                c = deep_clean_bale_dict(c['1'])
            if isinstance(c, dict) and c and all(isinstance(k, str) and k.isdigit() for k in c.keys()):
                unwrapped = [deep_clean_bale_dict(v) for k, v in sorted(c.items(), key=lambda x: int(x[0]))]
                cleaned_list.extend(unwrapped)
            else:
                cleaned_list.append(c)
        return cleaned_list
    return obj


def patch_add_message_function():
    """
    Patches aiobale.types.responses.message.add_message to safely handle NoneType context
    and prevent AttributeError: 'NoneType' object has no attribute 'get'.
    """
    if hasattr(msg_resp_module, "add_message"):
        _orig_add_msg = msg_resp_module.add_message
        def _safe_add_message(cls, v, info=None, *args, **kwargs):
            try:
                return _orig_add_msg(cls, v, info, *args, **kwargs)
            except AttributeError as ae:
                if "'NoneType' object has no attribute 'get'" in str(ae):
                    return v
                raise ae
        msg_resp_module.add_message = _safe_add_message

    for attr_name in dir(msg_resp_module):
        attr = getattr(msg_resp_module, attr_name)
        if isinstance(attr, type):
            if hasattr(attr, "add_message"):
                _orig_m = getattr(attr, "add_message")
                def _safe_m(cls, v, info=None, *args, **kwargs):
                    try:
                        return _orig_m(cls, v, info, *args, **kwargs)
                    except AttributeError as ae:
                        if "'NoneType' object has no attribute 'get'" in str(ae):
                            return v
                        raise ae
                setattr(attr, "add_message", classmethod(_safe_m))

patch_add_message_function()
logger.info("Successfully patched aiobale add_message validator for NoneType protection.")


app = Client()

if hasattr(app, "session"):
    app.session.client = app
    app.session._client = app


_orig_aiohttp_post = AiohttpSession.post

async def _patched_aiohttp_post(self, method, *args, **kwargs):
    """Pass-through wrapper forwarding native arguments to aiobale AiohttpSession.post."""
    return await _orig_aiohttp_post(self, method, *args, **kwargs)

AiohttpSession.post = _patched_aiohttp_post
# ==============================================================================


# Import submodules to register all commands
import modules
from modules.registry import route_command
from modules.groups import check_group_locks
from modules.utils import get_text_advanced, load_db, save_db
from modules.scheduler import run_background_scheduler


async def get_me_with_retry(app_client, max_retries: int = 5):
    """Safely fetches authenticated user profile with timeout and retry logic."""
    for attempt in range(1, max_retries + 1):
        try:
            logger.info(f"Authenticating with Bale server (Attempt {attempt}/{max_retries})...")
            me = await asyncio.wait_for(app_client.get_me(), timeout=20.0)
            if me:
                return me
        except (TimeoutError, asyncio.TimeoutError):
            logger.warning(f"Connection timeout on get_me() (Attempt {attempt}/{max_retries}). Retrying in 3 seconds...")
            await asyncio.sleep(3)
        except Exception as err:
            logger.error(f"Error during authentication attempt {attempt}: {err}")
            await asyncio.sleep(3)
    raise RuntimeError("Failed to authenticate with Bale server after multiple retries due to network timeout.")


async def main():
    async with app:
        me = await get_me_with_retry(app, max_retries=5)
        logger.info(f"Bale Self-Bot successfully authenticated as: {me.name} (ID: {me.id})")
        
        # Ensure known chats database list exists and seed with current group ID
        db = load_db()
        if "known_chats" not in db:
            db["known_chats"] = [5805101074]
            save_db(db)
        elif 5805101074 not in db["known_chats"]:
            db["known_chats"].append(5805101074)
            save_db(db)

        # Start background task scheduler
        asyncio.create_task(run_background_scheduler(app))
        logger.info("Background task scheduler initialized.")

        # Send startup notification
        try:
            if STARTUP_NOTIFICATION_CHAT:
                logger.info(f"Sending startup notification to {STARTUP_NOTIFICATION_CHAT}...")
                await asyncio.wait_for(
                    app.send_message(
                        chat_id=STARTUP_NOTIFICATION_CHAT,
                        text="🚀 **سلف‌بات بله فعال شد!**\nگروه «سلف سرویس» و تمام چت‌ها در حال پایش هستند.",
                        chat_type=ChatType.PRIVATE
                    ),
                    timeout=15.0
                )
                logger.info("Startup notification sent successfully.")
        except Exception as e:
            logger.debug(f"Startup notification status: {e}")

        last_mids = {}
        processed_mids = set()
        logger.info("Starting robust polling loop...")

        while True:
            try:
                # 1. Fetch active dialogs safely
                dialogs = []
                try:
                    dialogs = await asyncio.wait_for(app.load_dialogs(limit=25), timeout=15.0)
                except Exception:
                    pass  # Silently fallback to known_chats list

                # 2. Build target chats list
                chat_targets = []
                db = load_db()
                known_chats = db.get("known_chats", [5805101074])

                for d in dialogs:
                    c_type = int(d.peer.type)
                    if c_type in (1, 2):
                        chat_targets.append((d.peer.id, c_type))
                        if d.peer.id not in known_chats:
                            known_chats.append(d.peer.id)
                            db["known_chats"] = known_chats
                            save_db(db)

                # Fallback: Always poll known chats from database
                for known_id in known_chats:
                    if not any(c[0] == known_id for c in chat_targets):
                        c_type = 2 if (known_id > 1000000 or str(known_id).startswith("580")) else 1
                        chat_targets.append((known_id, c_type))

                # Always guarantee Saved Messages (me.id) is included
                if not any(c[0] == me.id for c in chat_targets):
                    chat_targets.insert(0, (me.id, 1))

                # 3. Poll recent messages across target chats (limit=3 to avoid missing commands)
                for chat_id, chat_type in chat_targets:
                    try:
                        history = await asyncio.wait_for(
                            app.load_history(chat_id=chat_id, chat_type=chat_type, limit=3),
                            timeout=10.0
                        )
                    except Exception:
                        continue

                    if not history:
                        continue

                    # Iterate chronological order to process oldest unhandled message first
                    for msg in reversed(history):
                        mid = getattr(msg, 'message_id', None)

                        # Detect unhandled messages
                        if mid and (mid not in processed_mids) and (chat_id not in last_mids or last_mids[chat_id] != mid):
                            last_mids[chat_id] = mid
                            processed_mids.add(mid)
                            if len(processed_mids) > 500:
                                processed_mids.clear()

                            raw_text = get_text_advanced(msg).strip()

                            logger.info(f"📌 [NEW MSG] Chat ID: {chat_id} | Sender: {msg.sender_id} | Text: '{raw_text}'")

                            # Permissions check
                            is_allowed = (msg.sender_id == me.id) or (msg.sender_id in WHITELISTED_USERS)

                            if is_allowed:
                                # CHECK EXPLICIT USER REPLIES TO AI MESSAGES
                                is_ai_reply = False
                                ai_ids = db.get("ai_msg_ids", [])

                                if mid not in ai_ids:
                                    replied_msg = getattr(msg, 'replied_to', None)
                                    if replied_msg and hasattr(replied_msg, 'message_id'):
                                        if replied_msg.message_id in ai_ids:
                                            is_ai_reply = True

                                if is_ai_reply:
                                    logger.info(f"🧠 [AI REPLY DETECTED] Continuing conversation in chat {chat_id}")
                                    from modules.ai import askgpt_command
                                    await askgpt_command(app, msg, chat_id, chat_type, args=raw_text)
                                else:
                                    await route_command(app, msg, chat_id, chat_type)
                            else:
                                await check_group_locks(app, msg, chat_id, chat_type)

                await asyncio.sleep(1.5)

            except (TimeoutError, asyncio.TimeoutError):
                logger.warning("Network request timed out in loop. Retrying in 3 seconds...")
                await asyncio.sleep(3)
            except Exception as e:
                if "rate_limited" in str(e).lower():
                    logger.warning("Rate limit warning detected, sleeping for 20 seconds...")
                    await asyncio.sleep(20)
                else:
                    logger.error(f"Error in polling loop: {e}", exc_info=True)
                    await asyncio.sleep(3)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        logger.info("Bot execution manually stopped.")