import inspect
import logging
from pydantic import BaseModel
import aiobale
import aiobale.types
import aiobale.types.responses.message as msg_resp_module
from aiobale.client.session.aiohttp import AiohttpSession

logger = logging.getLogger("ClientPatch")


def deep_clean_bale_dict(obj):
    """
    Recursively converts and unwraps dictionary representations with numeric string keys
    (e.g., {'1': ..., '2': ...}) generated by Bale API back into valid Python lists/objects.
    Fixes Pydantic ValidationError for DialogResponse and HistoryResponse in aiobale.
    """
    if isinstance(obj, dict):
        if obj and all(isinstance(k, str) and k.isdigit() for k in obj.keys()):
            sorted_items = [v for k, v in sorted(obj.items(), key=lambda x: int(x[0]))]
            cleaned_list = []
            for item in sorted_items:
                c = deep_clean_bale_dict(item)
                if isinstance(c, list):
                    cleaned_list.extend(c)
                else:
                    cleaned_list.append(c)
            return cleaned_list
        else:
            cleaned_dict = {}
            for k, v in obj.items():
                c_v = deep_clean_bale_dict(v)
                if isinstance(c_v, dict) and list(c_v.keys()) == ['1']:
                    c_v = deep_clean_bale_dict(c_v['1'])
                cleaned_dict[k] = c_v
            return cleaned_dict
    elif isinstance(obj, list):
        cleaned_list = []
        for item in obj:
            c = deep_clean_bale_dict(item)
            if isinstance(c, dict) and list(c.keys()) == ['1']:
                c = deep_clean_bale_dict(c['1'])
            if isinstance(c, dict) and c and all(isinstance(k, str) and k.isdigit() for k in c.keys()):
                unwrapped = [deep_clean_bale_dict(v) for k, v in sorted(c.items(), key=lambda x: int(x[0]))]
                cleaned_list.extend(unwrapped)
            else:
                cleaned_list.append(c)
        return cleaned_list
    return obj


def apply_runtime_patches(app_instance):
    """
    Applies all required runtime patches to aiobale and Pydantic v2 models.
    """
    # 1. Patch add_message validator for NoneType context protection
    if hasattr(msg_resp_module, "add_message"):
        _orig_add_msg = msg_resp_module.add_message
        def _safe_add_message(cls, v, info=None, *args, **kwargs):
            try:
                return _orig_add_msg(cls, v, info, *args, **kwargs)
            except AttributeError as ae:
                if "'NoneType' object has no attribute 'get'" in str(ae):
                    return v
                raise ae
        msg_resp_module.add_message = _safe_add_message

    for attr_name in dir(msg_resp_module):
        attr = getattr(msg_resp_module, attr_name)
        if isinstance(attr, type):
            if hasattr(attr, "add_message"):
                _orig_m = getattr(attr, "add_message")
                def _safe_m(cls, v, info=None, *args, **kwargs):
                    try:
                        return _orig_m(cls, v, info, *args, **kwargs)
                    except AttributeError as ae:
                        if "'NoneType' object has no attribute 'get'" in str(ae):
                            return v
                        raise ae
                setattr(attr, "add_message", classmethod(_safe_m))

    # 2. Patch AiohttpSession.post for Protobuf dict cleaning
    _orig_aiohttp_post = AiohttpSession.post

    async def _patched_aiohttp_post(self, method, *args, **kwargs):
        raw_res = await self.make_request(method, *args, **kwargs)
        cleaned_res = deep_clean_bale_dict(raw_res)

        client_ref = getattr(self, "client", None) or getattr(self, "_client", None) or app_instance
        ctx = {"client": client_ref}

        if hasattr(method, "__returning__") and method.__returning__:
            try:
                return method.__returning__.model_validate(cleaned_res, context=ctx)
            except AttributeError as ae:
                if "'NoneType' object has no attribute 'get'" in str(ae):
                    try:
                        return method.__returning__.model_validate(cleaned_res, context={"client": app_instance})
                    except Exception:
                        return method.__returning__.model_construct(**cleaned_res) if hasattr(method.__returning__, "model_construct") else cleaned_res
                raise ae
            except Exception:
                try:
                    return method.__returning__.model_validate(cleaned_res, context=ctx)
                except Exception:
                    return cleaned_res
        return cleaned_res

    AiohttpSession.post = _patched_aiohttp_post
    logger.info("Successfully applied runtime patches for aiobale Pydantic models.")